    google_analytics: G-S8RK8DJ0VS
    title: Diego Moore CV
    description: 
    url: https://diegomoore.github.io/cv # Or your GitHub Pages URL if you don't have a custom domain
    author: diego@mibstar.co.uk
